#spring.application.name=shopApp
server:
  port: 8080
  servlet:
    context-path: /shop

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/nvpShop"
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
